import { GoogleGenAI } from "@google/genai";

export const generateAIGlitch = async (
  base64Image: string, 
  promptDetails: string,
  apiKey: string
): Promise<string> => {
  if (!apiKey) throw new Error("API Key is missing");

  // Remove data URL prefix if present for Gemini
  const base64Data = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, "");

  const ai = new GoogleGenAI({ apiKey });
  
  const prompt = `
    Edit this image to apply a heavy digital glitch and datamosh effect.
    Aesthetic: Cyberpunk, corrupted video file, broken screen, signal noise, digital decay.
    Details: ${promptDetails || 'Aggressive color tearing, pixel displacement, and visual artifacts.'}
    Do not change the subject matter drastically, but heavily corrupt the visual presentation.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image', // Good for editing/generation
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/png', // Assuming PNG for canvas exports
              data: base64Data
            }
          },
          {
            text: prompt
          }
        ]
      }
    });

    // Check for image part in response
    if (response.candidates?.[0]?.content?.parts) {
        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData && part.inlineData.data) {
                return `data:image/png;base64,${part.inlineData.data}`;
            }
        }
    }
    
    throw new Error("No image generated by AI");

  } catch (error) {
    console.error("Gemini AI Error:", error);
    throw error;
  }
};